"use client";

import { useCallback, useEffect, useRef } from "react";

export default function ClickSpark({ sparkColor = "#ed5b3b", sparkSize = 9, sparkRadius = 18, sparkCount = 8, duration = 420, easing = "ease-out", extraScale = 1, children }) {
  const canvasRef = useRef(null); const sparksRef = useRef([]);
  useEffect(() => { const canvas = canvasRef.current; const parent = canvas?.parentElement; if (!canvas || !parent) return undefined; let resizeTimeout; const resize = () => { const { width, height } = parent.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1, 2); canvas.width = Math.floor(width * dpr); canvas.height = Math.floor(height * dpr); canvas.style.width = `${width}px`; canvas.style.height = `${height}px`; canvas.getContext("2d")?.setTransform(dpr, 0, 0, dpr, 0, 0); }; const ro = new ResizeObserver(() => { clearTimeout(resizeTimeout); resizeTimeout = setTimeout(resize, 100); }); ro.observe(parent); resize(); return () => { ro.disconnect(); clearTimeout(resizeTimeout); }; }, []);
  const easeFunc = useCallback(t => easing === "linear" ? t : easing === "ease-in" ? t * t : easing === "ease-in-out" ? (t < .5 ? 2 * t * t : -1 + (4 - 2 * t) * t) : t * (2 - t), [easing]);
  useEffect(() => { const canvas = canvasRef.current; const ctx = canvas?.getContext("2d"); if (!canvas || !ctx) return undefined; let animationId; const draw = timestamp => { const rect = canvas.getBoundingClientRect(); ctx.clearRect(0, 0, rect.width, rect.height); sparksRef.current = sparksRef.current.filter(spark => { const elapsed = timestamp - spark.startTime; if (elapsed >= duration) return false; const eased = easeFunc(elapsed / duration); const distance = eased * sparkRadius * extraScale; const length = sparkSize * (1 - eased); const x1 = spark.x + distance * Math.cos(spark.angle); const y1 = spark.y + distance * Math.sin(spark.angle); const x2 = spark.x + (distance + length) * Math.cos(spark.angle); const y2 = spark.y + (distance + length) * Math.sin(spark.angle); ctx.strokeStyle = sparkColor; ctx.globalAlpha = 1 - eased; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); return true; }); ctx.globalAlpha = 1; animationId = requestAnimationFrame(draw); }; animationId = requestAnimationFrame(draw); return () => cancelAnimationFrame(animationId); }, [sparkColor, sparkSize, sparkRadius, sparkCount, duration, easeFunc, extraScale]);
  const handleClick = e => { const canvas = canvasRef.current; if (!canvas) return; const rect = canvas.getBoundingClientRect(); const now = performance.now(); sparksRef.current.push(...Array.from({ length: sparkCount }, (_, i) => ({ x: e.clientX - rect.left, y: e.clientY - rect.top, angle: (2 * Math.PI * i) / sparkCount, startTime: now }))); };
  return <div className="click-spark" onClick={handleClick}>{children}<canvas ref={canvasRef} aria-hidden="true" /></div>;
}
