"use client";

import { useEffect, useRef, useState } from "react";
import "./GooeyNav.css";

export default function GooeyNav({ items = [], animationTime = 520, particleCount = 8, particleDistances = [70, 10], particleR = 80, timeVariance = 220, colors = [1, 2, 3, 1, 2, 3], initialActiveIndex = 0 }) {
  const containerRef = useRef(null); const navRef = useRef(null); const filterRef = useRef(null); const textRef = useRef(null); const [activeIndex, setActiveIndex] = useState(initialActiveIndex);
  const noise = (n = 1) => n / 2 - Math.random() * n;
  const getXY = (distance, index, total) => { const angle = ((360 + noise(8)) / total) * index * (Math.PI / 180); return [distance * Math.cos(angle), distance * Math.sin(angle)]; };
  const updateEffect = element => { if (!containerRef.current || !filterRef.current || !textRef.current) return; const base = containerRef.current.getBoundingClientRect(); const pos = element.getBoundingClientRect(); const style = { left: `${pos.x - base.x}px`, top: `${pos.y - base.y}px`, width: `${pos.width}px`, height: `${pos.height}px` }; Object.assign(filterRef.current.style, style); Object.assign(textRef.current.style, style); textRef.current.innerText = element.innerText; };
  const makeParticles = element => { element.style.setProperty("--time", `${animationTime * 2 + timeVariance}ms`); for (let i = 0; i < particleCount; i += 1) { const start = getXY(particleDistances[0], particleCount - i, particleCount); const end = getXY(particleDistances[1] + noise(7), particleCount - i, particleCount); const particle = document.createElement("span"); const point = document.createElement("span"); particle.className = "particle"; particle.style.setProperty("--start-x", `${start[0]}px`); particle.style.setProperty("--start-y", `${start[1]}px`); particle.style.setProperty("--end-x", `${end[0]}px`); particle.style.setProperty("--end-y", `${end[1]}px`); particle.style.setProperty("--time", `${animationTime * 2 + noise(timeVariance * 2)}ms`); particle.style.setProperty("--scale", `${1 + noise(.2)}`); particle.style.setProperty("--color", `var(--gooey-color-${colors[Math.floor(Math.random() * colors.length)]}, var(--orange))`); particle.style.setProperty("--rotate", `${noise(particleR / 10) * 10}deg`); point.className = "point"; particle.appendChild(point); element.appendChild(particle); requestAnimationFrame(() => element.classList.add("active")); setTimeout(() => particle.remove(), animationTime * 2 + timeVariance); } };
  const handleClick = (e, index) => { const li = e.currentTarget.closest?.("li") || e.currentTarget; if (activeIndex === index) return; setActiveIndex(index); updateEffect(li); textRef.current?.classList.remove("active"); void textRef.current?.offsetWidth; textRef.current?.classList.add("active"); if (filterRef.current) { filterRef.current.querySelectorAll(".particle").forEach(p => p.remove()); makeParticles(filterRef.current); } };
  useEffect(() => { const active = navRef.current?.querySelectorAll("li")[activeIndex]; if (active) { updateEffect(active); textRef.current?.classList.add("active"); } const ro = new ResizeObserver(() => { const current = navRef.current?.querySelectorAll("li")[activeIndex]; if (current) updateEffect(current); }); if (containerRef.current) ro.observe(containerRef.current); return () => ro.disconnect(); }, [activeIndex]);
  return <div className="gooey-nav-container" ref={containerRef}><nav><ul ref={navRef}>{items.map((item, index) => <li key={item.label} className={activeIndex === index ? "active" : ""}><a href={item.href} onClick={e => handleClick(e, index)} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); handleClick({ currentTarget: e.currentTarget.parentElement }, index); } }}>{item.label}</a></li>)}</ul></nav><span className="gooey-effect filter" ref={filterRef} /><span className="gooey-effect text" ref={textRef} /></div>;
}
